theme: minima
title: Inquid
author: INQUID SAS DE CV
email: luisarmando1324@gmail.com
description: Inquid businesses consulting
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
